CREATE TABLE proveedor (

	id_proveedor NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	nombre VARCHAR(100) NOT NULL,
	direccion VARCHAR(200) NOT NULL,
	telefono VARCHAR(20),
	PRIMARY KEY (id_proveedor)
);

CREATE TABLE tipo (

	id_tipo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	nombre VARCHAR(45) NOT NULL,
	PRIMARY KEY (id_tipo)
);

CREATE TABLE producto (

	id_producto NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	nombre CHAR(200) NOT NULL,
	medida CHAR(20) NOT NULL,
	id_tipo NUMBER NOT NULL,
	PRIMARY KEY (id_producto),
	FOREIGN KEY (id_tipo) REFERENCES tipo(id_tipo)
);

CREATE TABLE precio(

    id_precio NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    importe NUMBER NOT NULL,
    fecha_inicial DATE NOT NULL,
    fecha_final DATE NOT NULL,
    id_producto NUMBER NOT NULL,
    FOREIGN KEY(id_producto) REFERENCES producto(id_producto),
    PRIMARY KEY(id_precio)
);

CREATE TABLE compra(

    id_compra NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    fecha DATE NOT NULL,
    id_proveedor NUMBER NOT NULL,
    FOREIGN KEY(id_proveedor) REFERENCES proveedor(id_proveedor),
    PRIMARY KEY(id_compra)
);

CREATE TABLE compra_producto(

    id_compra_producto NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY, 
    id_compra NUMBER NOT NULL,
    id_producto NUMBER NOT NULL,
    cantidad INT,
    FOREIGN KEY(id_compra) REFERENCES compra(id_compra),
    FOREIGN KEY(id_producto) REFERENCES producto(id_producto),
    PRIMARY KEY(id_compra_producto)
);